### ISSUE TITLE
error function name "util.cal_psnr"

### ISSUE THREAD

**Issue by losehu** [wcy-cs/FishFSRNet#12]
<img width="692" alt="{92646789-0DC6-401C-B0D8-A6DEA1ABCA46}" src="https://github.com/user-attachments/assets/96c1def8-89f4-40ee-bd7f-4cf787a8d898">
* error function name ，the correct should be "util.calc_psnr"

**Comment by wcy-cs** [comment]
Thank you very much for your reminder. We have made the modifications.
