### ISSUE TITLE
no attribute 'astype' error in "calc_psnr"

### ISSUE THREAD

**Issue by losehu** [wcy-cs/FishFSRNet#13]
* my start train cmd is :
 pythonparsing/main_parsingnet.py --writer_name parsingnet --dir_data ./dataset --scale 4 --batch_size 2000  --save_path /home/jyp/save_results

* with error reported:
  File "/home/FishFSRNet-main/parsing/main_parsingnet.py", line 63, in <module>
    val_psnr_my = val_psnr_my + util.calc_psnr(hr[0].data.cpu(), sr[0].data.cpu())
  File "/home/FishFSRNet-main/parsing/util.py", line 74, in calc_psnr
    img1 = img1.astype(np.float64)
AttributeError: 'Tensor' object has no attribute 'astype'

*change code to:
def calc_psnr(img1, img2):
    img1 = img1.cpu().numpy().astype(np.float64)
    img2 = img2.cpu().numpy().astype(np.float64)
    
    mse = np.mean((img1 - img2) ** 2)
    if mse == 0:
        return float('inf')
    return 20 * math.log10(255.0 / math.sqrt(mse))

* solve the problem

**Comment by wcy-cs** [comment]
Thank you for your reminder.
