### ISSUE TITLE
训练集

### ISSUE THREAD

**Issue by lanyingyuexi** [wcy-cs/FishFSRNet#3]
您好，请问训练集是自己先预处理了Celeba，将其大小调整为128×128作为ground truth HR人脸，然后将ground truth的大小调整为64×64, 32×32和16×16作为相应的LR人脸，这个是分别放在不同的文件夹下并命名为LR等了吗？但好像与程序中的scale == 4，8,16对不太上。非常期待您的回答，谢谢！

**Comment by lanyingyuexi** [comment]
想问一下作者本篇论文采用的数据集的结构，方便的话可以提供一下数据集吗？十分感谢！

**Comment by wcy-cs** [comment]
您好,关于第一个我们是 把128x128作为HR，然后下采样到64×64, 32×32和16×16 分别命名为LR_x4 LR LR_x16。然后您的这句话“ 但好像与程序中的scale == 4，8,16对不太上。”我没太懂是什么意思。
关于数据集，您可以在这个链接 https://pan.baidu.com/s/18IvVDTVXBAcbPczt5afecg?pwd=nb2s 提取码:nb2s 获取。谢谢！

**Comment by lanyingyuexi** [comment]
> 您好,关于第一个我们是 把128x128作为HR，然后下采样到64×64, 32×32和16×16 分别命名为LR_x4 LR LR_x16。然后您的这句话“ 但好像与程序中的scale == 4，8,16对不太上。”我没太懂是什么意思。 关于数据集，您可以在这个链接 https://pan.baidu.com/s/18IvVDTVXBAcbPczt5afecg?pwd=nb2s 提取码:nb2s 获取。谢谢！

感谢您提供的数据集。我注意到数据集里的LR尺寸分别是32×32，16×16和8×8的，这样分别对应LR_x4 LR LR_x16。因为如果是64×64, 32×32和16×16 的话，扩大倍数分别为4,8,16的话，HR就变为了256x256了，而不是128x128这样理解对吗

**Comment by wcy-cs** [comment]
您好,我看了一下,应该是32x32, 16x16, 8x8，HR是128x128的。

**Comment by lanyingyuexi** [comment]
> 您好,我看了一下,应该是32x32, 16x16, 8x8，HR是128x128的。

好的。还有一个问题想请教，在dataset_parsingnet.py中  class Data(data.Dataset):  self.imgs_parsing_path = os.path.join(root, 'global_2_LR')里的global_2_LR是指的LR的人脸解析图的文件夹吗？这个是不是利用HR_parsing下采样得到呢？global_2_LR_x4和global_2_LR_x16也是同理。

**Comment by wcy-cs** [comment]
您好，我重新分享了一个链接，里面包含global_2数据，链接: https://pan.baidu.com/s/1dZn19SxyJaAKw0kBCzBt6A 提取码: i8nm

**Comment by lanyingyuexi** [comment]
> 您好，我重新分享了一个链接，里面包含global_2数据，链接: https://pan.baidu.com/s/1dZn19SxyJaAKw0kBCzBt6A 提取码: i8nm

十分感谢！
