### ISSUE TITLE
fishfsrnet.py训练代码

### ISSUE THREAD

**Issue by lanyingyuexi** [wcy-cs/FishFSRNet#4]
File "/FishFSRNet-main/fsr/fishfsrnet.py", line 98, in __init__
    self.reduc = common.channelReduction()
AttributeError: module 'common' has no attribute 'channelReduction'
您好，在运行python main_parsing.py训练整个网络时会出错，显示fishfsrnet.py中没有channelReduction，去到common.py中确实没有找到channelReduction的定义，请问这个common.channelReduction()表示的是什么呢？能否在common.py中添加对于的代码，感谢

**Comment by wcy-cs** [comment]
您好，不好意思哈，这个代码少点文件，我补充一下

**Comment by lanyingyuexi** [comment]
好的，感谢

**Comment by wcy-cs** [comment]
您好，已更新。
