### ISSUE TITLE
fishfsr的模型结构问题

### ISSUE THREAD

**Issue by lalagui** [wcy-cs/FishFSRNet#5]
您好，在运行fsr文件夹中main_parsing.py文件时，遇到下列问题：
TypeError: conv2d() received an invalid combination of arguments - got (Tensor, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Parameter, Parameter, tuple, tuple, tuple, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Parameter, Parameter, tuple, tuple, tuple, int)
请问是net结构的问题吗？应该怎么解决？期盼您的回复，感谢！

![fish](https://github.com/wcy-cs/FishFSRNet/assets/108655777/88f50ebe-4c81-4877-9cfb-e1ba4ba0f1c1)

**Comment by wcy-cs** [comment]
您好，代码已经更新，应该不会再有这个问题了。

**Comment by lalagui** [comment]
好的，非常感谢

**Comment by lalagui** [comment]
您好，对于fishfsrnet，我在训练时速度很慢，请问一下你们在celeba数据集上训练多少个epoch呀？

**Comment by wcy-cs** [comment]
不好意思，刚看到您的问题，具体训练多少个epoch有点记不太清了。

**Comment by wcy-cs** [comment]
您好，刚找了一下原来的代码，大概是跑了50个epoch。

**Comment by lalagui** [comment]
好的好的，非常感谢
