### ISSUE TITLE
关于提取人脸解析图

### ISSUE THREAD

**Issue by ivcagcowkh** [wcy-cs/FishFSRNet#6]
您好！请问是怎么通过BiSeNet来提取人脸解析图的？相关代码可以提供一下吗？感谢！

**Comment by wcy-cs** [comment]
您好！不好意思哈，这个代码有点久远，目前找不到了。我们当时是直接用预训练的模型对高分辨率人脸图像进行语义分割的。

**Comment by ivcagcowkh** [comment]
好的我试试。另外想问一下论文中实验设置那里“we adopt pretrained BiSeNet [75] to extract
parsing map of different facial components from HR and fuse.”，这里的fuse是什么？是LR图像的面部解析图吗？

**Comment by wcy-cs** [comment]
您好！是这样的，BiseNet是语义分割模型，会将人脸的头发、眼睛、鼻子、嘴巴、人脸都分割出来，但是我们论文中使用的解析图是在人脸的位置为1，五官和其他的位置是0，所以需要将BiSeNet分割得到的结果在融合到一起，得到我们论文中使用的解析图。

**Comment by ivcagcowkh** [comment]
好的！十分感谢您的解答！

**Comment by wcy-cs** [comment]
不客气
