### ISSUE TITLE
关于实验设置

### ISSUE THREAD

**Issue by ivcagcowkh** [wcy-cs/FishFSRNet#8]
作者您好！请问parsingnet和fishfsrnet在训练阶段都用的是CelebA中的168854张图像吗？另外想问一下两个训练阶段采用的epoch数目和batch size分别是多少呀！十分感谢

**Comment by wcy-cs** [comment]
您好！1）parsingnet和fishfsrnet在训练阶段都用的是CelebA中的168854张图像。2）训练阶段的epoch大概是50左右，batch size是8。

**Comment by ivcagcowkh** [comment]
好的谢谢

**Comment by ivcagcowkh** [comment]
请问两个训练阶段的学习率分别设置的是多少呢？是否有训练到后期学习率改变的操作呢？感谢！

**Comment by wcy-cs** [comment]
学习率都是1e-4，没有调整。

**Comment by ivcagcowkh** [comment]
好的，十分感谢回复！

**Comment by neverwinHao** [comment]
> 您好！1）parsingnet和fishfsrnet在训练阶段都用的是CelebA中的168854张图像。2）训练阶段的epoch大概是50左右，batch size是8。


您好，关于问题1)实验和训练集设置有点困惑。请问对于Helen*8的测试结果是**由CelebA这168854训练好的fishfsrnet模型测试**得到的还是重新使用Helen数据集单独训练和测试呢？

**Comment by wcy-cs** [comment]
您好，在本文中，helen和celeba分别训练一个模型，然后进行测试的。对于Helen*8的测试结果是重新使用Helen数据集单独训练和测试的。

**Comment by neverwinHao** [comment]
好的谢谢您的回复！






| |
l206457414
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年4月24日 15:47 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [wcy-cs/FishFSRNet] 关于实验设置 (Issue #8) |

您好，在本文中，helen和celeba分别训练一个模型，然后进行测试的。对于Helen*8的测试结果是重新使用Helen数据集单独训练和测试的。
